package sandbox

import (
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"
)

// The crafted-ext4 corpus (ST-3.3, dev/workspace-corpus/): images built with
// debugfs from the committed scripts, pushed through the real pipeline —
// listImage then extractImage — to assert what a hostile or merely exotic
// image makes the write-back do. mke2fs and debugfs are the same tools the
// product itself uses for packing; where they are missing the test says so
// and skips, because a corpus test that cannot build its images is not a
// failure of the code under test.
func buildCorpusImage(t *testing.T, script string) string {
	t.Helper()
	for _, tool := range []string{"mke2fs", "debugfs"} {
		if _, err := exec.LookPath(tool); err != nil {
			t.Skipf("%s is not installed — the corpus needs e2fsprogs to build its images", tool)
		}
	}
	image := filepath.Join(t.TempDir(), "corpus.ext4")
	// 512 1K blocks is enough for every script here and keeps the build under
	// a hundred milliseconds.
	out, err := exec.Command("mke2fs", "-F", "-t", "ext4", "-b", "1024", image, "512").CombinedOutput()
	if err != nil {
		t.Fatalf("mke2fs: %v: %s", err, out)
	}
	if out2, err := exec.Command("debugfs", "-w", "-f", script, image).CombinedOutput(); err != nil {
		t.Fatalf("debugfs -f %s: %v: %s", script, err, out2)
	}
	return image
}

// mustOsRoot is the extraction's own door: the *os.Root every sync-back
// writes through.
func mustOsRoot(t *testing.T, dir string) *os.Root {
	t.Helper()
	r, err := os.OpenRoot(dir)
	if err != nil {
		t.Fatalf("os.OpenRoot: %v", err)
	}
	return r
}

func TestWorkspaceCorpus_WhiteoutIsRefusedWholeImage(t *testing.T) {
	image := buildCorpusImage(t, "../../dev/workspace-corpus/whiteout.debugfs")
	root := t.TempDir()
	// The whiteout is refused at listing time — a char device's directory
	// record does not parse — which is the whole-image refusal arriving one
	// stage earlier than the extraction. Either stage refusing is the
	// contract; neither is a success.
	_, listErr := listImage(image)
	if listErr != nil {
		if !strings.Contains(listErr.Error(), "will not use") && !strings.Contains(listErr.Error(), "does not parse") {
			t.Fatalf("the whiteout refusal is not a shape refusal: %v", listErr)
		}
		if left, _ := os.ReadDir(root); len(left) != 0 {
			t.Fatalf("a refused image must leave the host directory untouched, got %d entries", len(left))
		}
		return
	}
	err := extractImage(image, mustList(t, image), mustOsRoot(t, root))
	if err == nil {
		t.Fatal("an image containing a char-device whiteout was extracted")
	}
	if !strings.Contains(err.Error(), "will not use") {
		t.Fatalf("the refusal is not the whole-image one: %v", err)
	}
	if left, _ := os.ReadDir(root); len(left) != 0 {
		t.Fatalf("a refused image must leave the host directory untouched, got %d entries", len(left))
	}
}

func mustList(t *testing.T, image string) []imageEntry {
	t.Helper()
	entries, err := listImage(image)
	if err != nil {
		t.Fatalf("listImage: %v", err)
	}
	return entries
}

func TestWorkspaceCorpus_SecurityXattrsAreNotRecreated(t *testing.T) {
	image := buildCorpusImage(t, "../../dev/workspace-corpus/xattrs-nuke.debugfs")
	entries, err := listImage(image)
	if err != nil {
		t.Fatalf("listImage on an xattr image: %v", err)
	}
	root := t.TempDir()
	if err := extractImage(image, entries, mustOsRoot(t, root)); err != nil {
		t.Fatalf("a security.* xattr must not refuse the file's contents: %v", err)
	}
	// The contents land; the LSM namespace does not ride along. A `security.*`
	// attribute needs privileges to set and none to lose, and a workspace
	// write-back is not in the business of labelling the user's project.
	blob, err := os.ReadFile(filepath.Join(root, "plain"))
	if err != nil {
		t.Fatalf("the file carrying the xattr did not land: %v", err)
	}
	if len(blob) == 0 {
		t.Fatal("the file landed empty")
	}
}

// The cross-platform-names image is generated by this test rather than by a
// committed script, because debugfs's `write` needs local files to copy from
// and the names themselves are the point: NFD stays NFD (the extractor is not
// in the normalisation business), and a `:` — legal on Linux, reserved by the
// macOS Finder — is preserved for the target platform to cope with.
func TestWorkspaceCorpus_NFDAndColonNamesExtractByteExact(t *testing.T) {
	for _, tool := range []string{"mke2fs", "debugfs"} {
		if _, err := exec.LookPath(tool); err != nil {
			t.Skipf("%s is not installed — the corpus needs e2fsprogs to build its images", tool)
		}
	}
	dir := t.TempDir()
	image := filepath.Join(dir, "names.ext4")
	if out, err := exec.Command("mke2fs", "-F", "-t", "ext4", "-b", "1024", image, "512").CombinedOutput(); err != nil {
		t.Fatalf("mke2fs: %v: %s", err, out)
	}
	names := []string{"cafe\u0301.txt", "12:30.txt"}
	script := filepath.Join(dir, "names.debugfs")
	var sb strings.Builder
	sb.WriteString("cd /\n")
	for i, name := range names {
		local := filepath.Join(dir, "src"+string(rune('a'+i)))
		if err := os.WriteFile(local, []byte(name), 0o644); err != nil {
			t.Fatal(err)
		}
		sb.WriteString("write " + local + " /" + name + "\n")
	}
	if err := os.WriteFile(script, []byte(sb.String()), 0o644); err != nil {
		t.Fatal(err)
	}
	if out, err := exec.Command("debugfs", "-w", "-f", script, image).CombinedOutput(); err != nil {
		t.Fatalf("debugfs: %v: %s", err, out)
	}
	entries, err := listImage(image)
	if err != nil {
		t.Fatalf("listImage: %v", err)
	}
	root := filepath.Join(dir, "out")
	if err := os.MkdirAll(root, 0o755); err != nil {
		t.Fatal(err)
	}
	if err := extractImage(image, entries, mustOsRoot(t, root)); err != nil {
		t.Fatalf("cross-platform names must extract on Linux: %v", err)
	}
	for _, name := range names {
		if _, err := os.Stat(filepath.Join(root, name)); err != nil {
			t.Errorf("name %q did not land: %v", name, err)
		}
	}
}

func TestWorkspaceCorpus_DirectoryHardlinkDoesNotPanicOrLoop(t *testing.T) {
	image := buildCorpusImage(t, "../../dev/workspace-corpus/dir-hardlink.debugfs")
	root := t.TempDir()
	// ext4 corruption via debugfs's own ln: a second name for a directory.
	// Whatever the pipeline decides — refuse, skip, or extract — it must
	// terminate. The corpus records the shape; the assertion is the
	// termination and the absence of a panic.
	entries, err := listImage(image)
	if err == nil {
		_ = extractImage(image, entries, mustOsRoot(t, root))
	}
}

func TestWorkspaceCorpus_ShortImageFailsCleanly(t *testing.T) {
	image := buildCorpusImage(t, "../../dev/workspace-corpus/xattrs-nuke.debugfs")
	// F17's shape: a short dump. The file exists; its tail is gone. The read
	// must fail cleanly rather than produce a tree somebody trusts.
	if err := os.Truncate(image, 4096); err != nil {
		t.Fatalf("truncate: %v", err)
	}
	if _, err := listImage(image); err == nil {
		t.Fatal("a truncated image listed without complaint")
	}
}
