// Command gendocs writes docs/reference from the product itself (E3-1).
//
// Nothing here is a second opinion about what KelyfOS does. The command list and
// every flag come from running the CLI's own `-h`, so what the reference prints
// is what a user is shown. The MCP tools come from running the supervisor's
// --dump-tools, so they are the guest's own `tools/list` answer. The toml keys,
// the event types and the exit codes come from tables the product depends on:
// config.Schema() builds the parser's unknown-key errors, recorder.Types()
// carries the fields the writer sets, exitcode is what the CLI returns.
//
// It also verifies before it writes, because generation alone is not enough. A
// command that exists and is missing from the usage block would be silently
// absent from the reference, so the dispatch switch in host/main.go is read and
// compared. The equivalent checks for keys and event types live as tests beside
// the tables they check.
//
// `make docs` runs this; CI runs `make docs` and fails on any diff (F-D4).
package main

import (
	"encoding/json"
	"flag"
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"sort"
	"strconv"
	"strings"

	"github.com/p4r4n0rm4l/KelyfOS/internal/config"
	"github.com/p4r4n0rm4l/KelyfOS/internal/denial"
	"github.com/p4r4n0rm4l/KelyfOS/internal/exitcode"
	"github.com/p4r4n0rm4l/KelyfOS/internal/mcp"
	"github.com/p4r4n0rm4l/KelyfOS/internal/recorder"
)

const banner = `<!-- Generated by ` + "`make docs`" + `. Do not edit: your changes will be overwritten,
     and CI fails when this file disagrees with the source (F-D4). -->
`

func main() {
	bin := flag.String("bin", "bin/kelyfos", "the kelyfos CLI to interrogate")
	sup := flag.String("supervisor", "", "a host build of the guest supervisor, for its tool list")
	out := flag.String("out", "docs/reference", "directory to write")
	repo := flag.String("repo", ".", "repository root, for the source checks")
	flag.Parse()

	if err := run(*bin, *sup, *out, *repo); err != nil {
		fmt.Fprintln(os.Stderr, "gendocs:", err)
		os.Exit(1)
	}
}

func run(bin, sup, out, repo string) error {
	cmds, err := commands(bin)
	if err != nil {
		return err
	}
	if err := checkDispatch(repo, cmds); err != nil {
		return err
	}
	if err := checkDenialsRaised(repo); err != nil {
		return err
	}
	if err := os.MkdirAll(out, 0o755); err != nil {
		return err
	}

	files := map[string]string{
		"README.md":     indexPage(),
		"cli.md":        cliPage(cmds),
		"config.md":     configPage(),
		"denials.md":    denialsPage(),
		"events.md":     eventsPage(),
		"exit-codes.md": exitPage(),
	}
	if sup != "" {
		page, err := toolsPage(sup, bin)
		if err != nil {
			return err
		}
		files["tools.md"] = page
		prof, err := profilesPage(sup)
		if err != nil {
			return err
		}
		files["profiles.md"] = prof
	}
	for name, body := range files {
		if err := os.WriteFile(filepath.Join(out, name), []byte(body), 0o644); err != nil {
			return err
		}
	}
	fmt.Printf("gendocs: wrote %d files to %s\n", len(files), out)

	// The two machine-reader files at the repository root (E3-2). They are
	// written last because llms-full.txt concatenates what was just generated.
	full, err := llmsFull(repo)
	if err != nil {
		return err
	}
	index := llmsIndex(tokenEstimate(full))
	for name, body := range map[string]string{"llms.txt": index, "llms-full.txt": full} {
		if err := os.WriteFile(filepath.Join(repo, name), []byte(body), 0o644); err != nil {
			return err
		}
	}
	fmt.Printf("gendocs: llms.txt %d bytes · llms-full.txt %d bytes, about %d tokens "+
		"at %.2f characters each (an estimate, not a measurement)\n",
		len(index), len(full), tokenEstimate(full), charsPerToken)
	return nil
}

// --- the CLI -----------------------------------------------------------------

// Command is one subcommand, with the flags its own flagset defines.
type Command struct {
	Name  string // "run", or "snapshot save"
	Usage string // the argument shape from the usage block, e.g. "[flags] <command>"
	Doc   string
	Flags []Flag
}

// Flag is one line of flag.PrintDefaults output, taken apart.
type Flag struct {
	Name    string
	Type    string // flag's own name for the value: string, int, duration, …
	Doc     string
	Default string
}

var (
	usageLine = regexp.MustCompile(`^  kelyfos (\S+)(.*)$`)
	gap       = regexp.MustCompile(`\s{2,}`)
	flagLine  = regexp.MustCompile(`^  -(\S+)(?: (.*))?$`)
	// A one-letter boolean is the one shape `flag` formats differently: it puts
	// the usage on the *same* line after a tab, because "  -x" is short enough
	// to leave room. flagLine cannot match that — it wants a space or an end of
	// line after the name — so every such flag was silently dropped from the
	// generated reference, and neither the generator nor the drift gate could
	// notice, because the committed file agreed with the generator and both
	// were missing it. `kelyfos log -f` was undocumented from the day it was
	// added until P6-1 went looking.
	flagInline = regexp.MustCompile("^  -(\\S+)\t(.*)$")
	defaultAt  = regexp.MustCompile(`\s*\(default:? (.*)\)$`)
	// The architecture flags default to whatever machine ran the generator, so
	// the value is replaced rather than recorded. It is the only host-dependent
	// default in the CLI; anything else that appears here would make `make docs`
	// produce a different file on every machine, which CI would then fail on.
	archDefault = regexp.MustCompile(`^"(aarch64|x86_64)"$`)
)

// commands reads the CLI's own usage block. A command a user cannot discover
// from `kelyfos help` is a command that is not really there, and checkDispatch
// makes sure the block is complete.
func commands(bin string) ([]Command, error) {
	text, err := capture(bin, "help")
	if err != nil {
		return nil, fmt.Errorf("asking %s for its usage: %w", bin, err)
	}
	// One entry per line of the usage block first, so a wrapped description
	// reaches the entry it belongs to before subcommands multiply it.
	type entry struct{ name, shape, doc string }
	var entries []entry
	for _, line := range strings.Split(text, "\n") {
		m := usageLine.FindStringSubmatch(line)
		if m == nil {
			if len(entries) > 0 && strings.HasPrefix(line, "     ") && strings.TrimSpace(line) != "" {
				entries[len(entries)-1].doc += " " + strings.TrimSpace(line)
			}
			continue
		}
		// m[2] keeps its leading whitespace on purpose: the gap between the
		// argument shape and the description is what separates them, and a
		// command with no arguments starts with that gap.
		var shape, doc string
		if parts := gap.Split(m[2], 2); len(parts) == 2 {
			shape, doc = strings.TrimSpace(parts[0]), strings.TrimSpace(parts[1])
		} else {
			shape = strings.TrimSpace(m[2])
		}
		entries = append(entries, entry{name: m[1], shape: shape, doc: doc})
	}

	var cmds []Command
	for _, e := range entries {
		subs := []string{""}
		shape := e.shape
		if strings.Contains(shape, "|") {
			first := strings.Fields(shape)[0]
			subs = strings.Split(first, "|")
			shape = strings.TrimSpace(strings.TrimPrefix(shape, first))
		}
		for _, sub := range subs {
			full := e.name
			if sub != "" {
				full = e.name + " " + sub
			}
			cmds = append(cmds, Command{Name: full, Usage: shape, Doc: e.doc})
		}
	}
	if len(cmds) == 0 {
		return nil, fmt.Errorf("%s help printed no commands", bin)
	}

	for i := range cmds {
		fl, err := flagsOf(bin, cmds[i].Name)
		if err != nil {
			return nil, err
		}
		cmds[i].Flags = fl
	}
	return cmds, nil
}

// flagsOf asks a command for its own flags. `flag` writes them itself, so this
// reads the definitions rather than restating them.
func flagsOf(bin, name string) ([]Flag, error) {
	switch name {
	case "version", "help":
		return nil, nil // no flagset at all
	}
	args := append(strings.Fields(name), "-h")
	text, err := capture(bin, args...)
	if err != nil {
		return nil, fmt.Errorf("asking for `%s -h`: %w", name, err)
	}
	return parseFlags(text), nil
}

// parseFlags takes `flag.PrintDefaults` output apart. Split out of flagsOf so a
// test can feed it the real thing rather than a hand-written imitation: the bug
// this function was carrying was a disagreement with how `flag` actually formats
// a line, and a test that writes its own lines would have agreed with the bug.
func parseFlags(text string) []Flag {
	var out []Flag
	lines := strings.Split(text, "\n")
	for i := 0; i < len(lines); i++ {
		// The same-line form first: its tab would otherwise be read as part of
		// nothing at all, and the flag would vanish.
		if m := flagInline.FindStringSubmatch(lines[i]); m != nil {
			f := Flag{Name: m[1], Type: "boolean"}
			f.Doc, f.Default = docAndDefault(m[2])
			out = append(out, f)
			continue
		}
		m := flagLine.FindStringSubmatch(lines[i])
		if m == nil {
			continue
		}
		f := Flag{Name: m[1], Type: strings.TrimSpace(m[2])}
		if f.Type == "" {
			// flag prints no type name for a bool, because -x is the whole of it.
			f.Type = "boolean"
		}
		if i+1 < len(lines) && strings.HasPrefix(lines[i+1], "    \t") {
			f.Doc, f.Default = docAndDefault(lines[i+1])
			i++
		}
		if f.Name == "arch" && archDefault.MatchString(f.Default) {
			f.Default = "the build host's architecture"
		}
		out = append(out, f)
	}
	return out
}

// docAndDefault splits a usage string from the "(default X)" tail flag appends.
func docAndDefault(s string) (doc, def string) {
	doc = strings.TrimSpace(s)
	if d := defaultAt.FindStringSubmatch(doc); d != nil {
		def = d[1]
		doc = defaultAt.ReplaceAllString(doc, "")
	}
	return doc, def
}

// capture runs the binary and returns everything it printed. A command asked for
// its own help exits 2, which is not a failure here.
func capture(bin string, args ...string) (string, error) {
	cmd := exec.Command(bin, args...)
	var buf strings.Builder
	cmd.Stdout = &buf
	cmd.Stderr = &buf
	err := cmd.Run()
	if _, ok := err.(*exec.ExitError); err != nil && !ok {
		return "", err
	}
	if buf.Len() == 0 {
		return "", fmt.Errorf("%s %s printed nothing", bin, strings.Join(args, " "))
	}
	return buf.String(), nil
}

// checkDispatch reads host/main.go and fails if the dispatch switch knows a
// command the usage block does not. Generation cannot notice an absence, so this
// is the part that does.
func checkDispatch(repo string, cmds []Command) error {
	documented := map[string]bool{}
	for _, c := range cmds {
		documented[strings.Fields(c.Name)[0]] = true
	}
	// Aliases of a documented command, not commands of their own. `logs` is
	// `log`: both names get typed, one implementation answers to both, and the
	// usage block says so on the line for `log` rather than giving the same
	// flag table twice.
	for _, alias := range []string{"--version", "-v", "-h", "--help", "logs"} {
		documented[alias] = true
	}

	path := filepath.Join(repo, "host", "main.go")
	fset := token.NewFileSet()
	file, err := parser.ParseFile(fset, path, nil, 0)
	if err != nil {
		return err
	}
	var missing []string
	ast.Inspect(file, func(n ast.Node) bool {
		fn, ok := n.(*ast.FuncDecl)
		if !ok || fn.Name.Name != "main" {
			return true
		}
		ast.Inspect(fn.Body, func(n ast.Node) bool {
			cc, ok := n.(*ast.CaseClause)
			if !ok {
				return true
			}
			for _, e := range cc.List {
				lit, ok := e.(*ast.BasicLit)
				if !ok || lit.Kind != token.STRING {
					continue
				}
				if v, err := strconv.Unquote(lit.Value); err == nil && !documented[v] {
					missing = append(missing, v)
				}
			}
			return true
		})
		return true
	})
	if len(missing) > 0 {
		sort.Strings(missing)
		return fmt.Errorf("host/main.go dispatches %s, and `kelyfos help` does not list %s.\n"+
			"A command nobody can discover is not documented by generating harder: add it to the "+
			"usage block in host/main.go",
			strings.Join(quoteAll(missing), ", "), plural(len(missing), "it", "them"))
	}
	return nil
}

func quoteAll(ss []string) []string {
	out := make([]string, len(ss))
	for i, s := range ss {
		out[i] = strconv.Quote(s)
	}
	return out
}

func plural(n int, one, many string) string {
	if n == 1 {
		return one
	}
	return many
}

// --- pages -------------------------------------------------------------------

func indexPage() string {
	var b strings.Builder
	b.WriteString(banner)
	b.WriteString(`
# KelyfOS reference

Generated from the source on every build. Each page below is extracted rather
than written, so a flag that exists cannot be missing from it and a flag it
lists cannot be one that was removed.

| Page | Extracted from |
| --- | --- |
| [cli.md](cli.md) | the CLI's own ` + "`-h`" + ` output, for every command |
| [config.md](config.md) | the ` + "`kelyfos.toml`" + ` parser's key schema |
| [tools.md](tools.md) | the guest supervisor's ` + "`tools/list`" + ` answer |
| [events.md](events.md) | the flight recorder's event schema |
| [exit-codes.md](exit-codes.md) | the exit statuses the CLI returns |
| [denials.md](denials.md) | the refusal catalog, and the fix line each one carries |
| [profiles.md](profiles.md) | the guest confinement profiles, from the supervisor's own dump |

The prose that explains *why* any of it is shaped this way is in the documents
[one level up](../README.md); this directory is the part a machine should read
when it needs an exact name.
`)
	return b.String()
}

func cliPage(cmds []Command) string {
	var b strings.Builder
	b.WriteString(banner)
	b.WriteString("\n# CLI reference\n\nEvery command and every flag, from each command's own flag set.\n" +
		"Go's `flag` accepts one dash or two, so `-image` and `--image` are the same flag.\n\n")

	b.WriteString("| Command | What it does |\n| --- | --- |\n")
	for _, c := range cmds {
		b.WriteString(fmt.Sprintf("| [`kelyfos %s`](#kelyfos-%s) | %s |\n",
			c.Name, strings.ReplaceAll(c.Name, " ", "-"), or(c.Doc, "—")))
	}

	for _, c := range cmds {
		fmt.Fprintf(&b, "\n## kelyfos %s\n\n", c.Name)
		if c.Doc != "" {
			fmt.Fprintf(&b, "%s.\n\n", strings.ToUpper(c.Doc[:1])+c.Doc[1:])
		}
		fmt.Fprintf(&b, "```\n%s\n```\n\n", strings.TrimSpace("kelyfos "+c.Name+" "+c.Usage))
		if len(c.Flags) == 0 {
			b.WriteString("No flags.\n")
			continue
		}
		b.WriteString("| Flag | Type | Default | Meaning |\n| --- | --- | --- | --- |\n")
		for _, f := range c.Flags {
			// A one-letter flag is written with one dash, because that is how
			// anybody writes it and how the CLI's own help prints it. Go's flag
			// package accepts either for both, so this is about the reader.
			dashes := "--"
			if len(f.Name) == 1 {
				dashes = "-"
			}
			fmt.Fprintf(&b, "| `%s%s` | %s | %s | %s |\n",
				dashes, f.Name, or(f.Type, "—"), or(f.Default, "—"), or(cell(f.Doc), "—"))
		}
	}
	return b.String()
}

func configPage() string {
	var b strings.Builder
	b.WriteString(banner)
	b.WriteString("\n# `kelyfos.toml` reference\n\n" +
		"Every key the parser understands, and every key it refuses on purpose.\n" +
		"Anything not listed here is an error naming the line — the file never\n" +
		"skips a key it does not recognise.\n")

	for _, s := range Sections() {
		fmt.Fprintf(&b, "\n## `%s`\n\n%s.\n\n", s.Header, strings.ToUpper(s.Doc[:1])+s.Doc[1:])
		keys := config.KeysIn(s.Name)
		if len(keys) == 0 {
			b.WriteString("No keys.\n")
			continue
		}
		b.WriteString("| Key | Type | Default | Meaning |\n| --- | --- | --- | --- |\n")
		for _, k := range keys {
			meaning := cell(k.Doc)
			switch {
			case k.Refused != "":
				meaning = "**refused** — " + cell(k.Refused)
			case k.RefusedLater != "":
				meaning = cell(k.Doc) + " · **" + cell(k.RefusedLater) + "**"
			}
			fmt.Fprintf(&b, "| `%s` | %s | %s | %s |\n",
				k.Name, k.Type, or(cell(k.Default), "—"), meaning)
		}
	}
	return b.String()
}

// Sections is config.Sections, reachable here so the page and the parser cannot
// disagree about which headers exist.
func Sections() []config.Section { return config.Sections() }

func eventsPage() string {
	var b strings.Builder
	b.WriteString(banner)
	b.WriteString("\n# Flight-recorder events\n\n" +
		"Every event type the host writes, with its payload. The concepts — why the\n" +
		"host writes all of it, what the hash chain does and does not prove — are in\n" +
		"[`../events.md`](../events.md).\n\n## Common fields\n\n" +
		"On every event, in the order the hash is computed over.\n\n")
	writeFields(&b, recorder.CommonFields())

	for _, e := range recorder.Types() {
		fmt.Fprintf(&b, "\n## `%s`\n\n%s. Written by the **%s**.\n\n",
			e.Type, strings.ToUpper(e.Doc[:1])+e.Doc[1:], e.Source)
		writeFields(&b, e.Fields)
	}
	return b.String()
}

func writeFields(b *strings.Builder, fields []recorder.Field) {
	b.WriteString("| Field | Type | Meaning |\n| --- | --- | --- |\n")
	for _, f := range fields {
		doc := cell(f.Doc)
		if f.When != "" {
			doc += " *(" + cell(f.When) + ")*"
		}
		fmt.Fprintf(b, "| `%s` | %s | %s |\n", f.Name, f.Type, doc)
	}
}

// denialsPage is the refusal catalog (E5-4). Every entry is printed as it is
// actually raised — message, ID and fix line, rendered with the entry's own
// sample values — so this page is a page of real refusals rather than a page of
// templates. What a reader matches against what their terminal showed them is
// the same string, built by the same code.
func denialsPage() string {
	var b strings.Builder
	b.WriteString(banner)
	b.WriteString("\n# Denials\n\n" +
		"Every refusal that carries an ID, with the fix. A refusal prints its ID in\n" +
		"brackets; that ID is the heading to look for here.\n\n" +
		"Refusals raised while reading `kelyfos.toml` or validating a team plan are not\n" +
		"here: they name their own file and line instead of an ID, because the thing to\n" +
		"go and look at is the line you wrote.\n\n" +
		"Failures are not here. \"The upstream did not answer\" is not a refusal, has no\n" +
		"fix line, and nothing you type changes it.\n")
	for _, d := range denial.All() {
		fmt.Fprintf(&b, "\n## `%s`\n\n%s.\n\n```\n%s\n```\n",
			d.ID, sentence(d.Doc), d.Render(d.Sample))
		if p := d.Placeholders(); len(p) > 0 {
			fmt.Fprintf(&b, "\nNamed: %s. The values above are an example.\n", code(p))
		}
	}
	return b.String()
}

// sentence makes a catalog Doc — written lowercase, like every other table in
// this repository — stand on its own under a heading.
func sentence(s string) string {
	s = strings.TrimSuffix(s, ".")
	if s == "" {
		return s
	}
	return strings.ToUpper(s[:1]) + s[1:]
}

func code(names []string) string {
	out := make([]string, len(names))
	for i, n := range names {
		out[i] = "`" + n + "`"
	}
	return strings.Join(out, ", ")
}

// checkDenialsRaised fails the build when a catalog entry is raised nowhere.
//
// The catalog is only worth having if it is the refusals the product actually
// makes. An entry nothing raises is a promise in the documentation with no code
// behind it, which is exactly the failure the generated reference exists to
// prevent (F-D4) — so it is checked in the same place, by reading which
// `denial.X` identifiers the non-test source mentions.
func checkDenialsRaised(repo string) error {
	names, err := denialNames(filepath.Join(repo, "internal", "denial", "denial.go"))
	if err != nil {
		return err
	}
	raised := map[string]bool{}
	fset := token.NewFileSet()
	for _, dir := range []string{"host", "internal", "supervisor"} {
		err := filepath.WalkDir(filepath.Join(repo, dir), func(path string, e os.DirEntry, err error) error {
			if err != nil || e.IsDir() || !strings.HasSuffix(path, ".go") ||
				strings.HasSuffix(path, "_test.go") ||
				strings.Contains(path, filepath.Join("internal", "denial")) {
				return err
			}
			f, err := parser.ParseFile(fset, path, nil, 0)
			if err != nil {
				return err
			}
			ast.Inspect(f, func(n ast.Node) bool {
				sel, ok := n.(*ast.SelectorExpr)
				if !ok {
					return true
				}
				if id, ok := sel.X.(*ast.Ident); ok && id.Name == "denial" {
					raised[sel.Sel.Name] = true
				}
				return true
			})
			return nil
		})
		if err != nil {
			return err
		}
	}
	var unraised []string
	for name, id := range names {
		if !raised[name] {
			unraised = append(unraised, id)
		}
	}
	if len(unraised) > 0 {
		sort.Strings(unraised)
		return fmt.Errorf("the denial catalog lists %s, and nothing raises %s.\n"+
			"A refusal documented but never made is a promise with no code behind it: "+
			"raise it where it belongs, or delete the entry from internal/denial",
			strings.Join(quoteAll(unraised), ", "), plural(len(unraised), "it", "them"))
	}
	return nil
}

// denialNames reads the catalog's own source for the Go identifier of each
// entry and the ID it carries, so the check can report the ID a person reads
// rather than the variable a programmer typed.
func denialNames(path string) (map[string]string, error) {
	fset := token.NewFileSet()
	file, err := parser.ParseFile(fset, path, nil, 0)
	if err != nil {
		return nil, err
	}
	names := map[string]string{}
	ast.Inspect(file, func(n ast.Node) bool {
		vs, ok := n.(*ast.ValueSpec)
		if !ok || len(vs.Names) != 1 || len(vs.Values) != 1 {
			return true
		}
		lit, ok := vs.Values[0].(*ast.CompositeLit)
		if !ok {
			return true
		}
		if id, ok := lit.Type.(*ast.Ident); !ok || id.Name != "Denial" {
			return true
		}
		for _, el := range lit.Elts {
			kv, ok := el.(*ast.KeyValueExpr)
			if !ok {
				continue
			}
			if k, ok := kv.Key.(*ast.Ident); !ok || k.Name != "ID" {
				continue
			}
			if s, ok := kv.Value.(*ast.BasicLit); ok && s.Kind == token.STRING {
				if v, err := strconv.Unquote(s.Value); err == nil {
					names[vs.Names[0].Name] = v
				}
			}
		}
		return true
	})
	if len(names) == 0 {
		return nil, fmt.Errorf("no denial entries found in %s", path)
	}
	return names, nil
}

func exitPage() string {
	var b strings.Builder
	b.WriteString(banner)
	b.WriteString("\n# Exit codes\n\n" +
		"What `kelyfos` itself returns. A status from something KelyfOS ran passes\n" +
		"through unchanged, so these codes are not the whole range: `kelyfos exec` and\n" +
		"`kelyfos shell` carry the guest command's status, and `kelyfos run -- <cmd>`\n" +
		"carries the host command's.\n\n")
	b.WriteString("| Code | Meaning |\n| --- | --- |\n")
	for _, c := range exitcode.All() {
		fmt.Fprintf(&b, "| `%d` | %s |\n", c.Code, cell(c.Doc))
	}
	return b.String()
}

type toolDump struct {
	Base      []mcp.Tool `json:"base"`
	Team      []mcp.Tool `json:"team"`
	TeamSpawn []mcp.Tool `json:"team_spawn"`
}

// profilesPage is the guest confinement every flavor applies, asked of the
// supervisor rather than transcribed from it (P5-3).
//
// The page is deliberately architecture-independent: it prints syscall names and
// never their numbers. A refusal list is numbers by the time the kernel sees it
// and the same name is a different number on another architecture, so a page
// built from numbers would fail its own drift check depending on which machine
// ran `make docs`. `kelyfos-supervisor --dump-profile` prints the resolved
// numbers for the machine it runs on, and the acceptance reads them there.
// backticked joins paths as an inline code list, in the order the profile named
// them: the order is the order the rules are applied in, not alphabetical.
func backticked(paths []string) string {
	q := make([]string, len(paths))
	for i, p := range paths {
		q[i] = "`" + p + "`"
	}
	return strings.Join(q, ", ")
}

func profilesPage(sup string) (string, error) {
	out, err := exec.Command(sup, "--dump-profile", "base", "dev").Output()
	if err != nil {
		return "", fmt.Errorf("supervisor --dump-profile: %w", err)
	}

	type profile struct {
		name        string
		arch        string
		abi         string
		write       []string
		writeTree   []string
		writeDevice []string
		refused     []string
	}
	var profiles []profile
	var cur *profile
	for _, line := range strings.Split(string(out), "\n") {
		f := strings.Fields(line)
		if len(f) == 0 {
			continue
		}
		switch f[0] {
		case "flavor":
			profiles = append(profiles, profile{name: f[1]})
			cur = &profiles[len(profiles)-1]
		case "arch":
			cur.arch = f[1]
		case "landlock-abi-min":
			cur.abi = f[1]
		case "write":
			cur.write = append(cur.write, f[1])
		case "write-tree":
			cur.writeTree = append(cur.writeTree, f[1])
		case "write-device":
			cur.writeDevice = append(cur.writeDevice, f[1])
		case "refuse":
			// The name only. A syscall's number is the architecture's, and
			// `make docs` runs on whichever architecture CI uses, so a page
			// built from numbers would fail its own diff check on the other
			// one. The numbers are in `supervisor --dump-profile`, which the
			// acceptance reads.
			cur.refused = append(cur.refused, "`"+f[1]+"`")
		}
	}
	if len(profiles) == 0 {
		return "", fmt.Errorf("supervisor --dump-profile described no flavors")
	}

	var b strings.Builder
	b.WriteString(banner)
	b.WriteString("# Guest confinement profiles\n\n")
	b.WriteString("What the supervisor grants every process it spawns \u2014 `exec`, a plugin, and the\n" +
		"interactive shell alike. It is applied by a re-exec of the supervisor that restricts\n" +
		"itself and then runs the real program, so the restrictions belong to the child and\n" +
		"never to the supervisor. [`../hardening.md`](../hardening.md) \u00a74 says why each\n" +
		"mechanism is here and what it does not do.\n\n")
	b.WriteString("**Landlock** governs the filesystem: the listed trees are writable, everything\n" +
		"else on the image is readable and executable, and nothing else is writable. The\n" +
		"device trees are writable the same way the others are \u2014 a program may create files\n" +
		"and directories under them \u2014 which for `/dev/shm` means a general-purpose writable\n" +
		"area the guest kernel sizes at half the machine's RAM. The named device nodes are\n" +
		"narrower: read, write and truncate that file, and nothing else.\n" +
		"**seccomp** refuses the listed syscalls with `EPERM` \u2014 a refusal list rather than\n" +
		"an allowlist, because an allowlist for an arbitrary agent command is a crash waiting\n" +
		"to be mistaken for a security feature.\n\n")
	b.WriteString("The policy is the same on every architecture KelyfOS builds for. A name that is\n" +
		"not a syscall on some architecture \u2014 `settimeofday` has none on aarch64, which has\n" +
		"only `clock_settime` \u2014 is absent from that build's filter rather than faked, and\n" +
		"`kelyfos-supervisor --dump-profile` prints the resolved numbers for the machine it\n" +
		"runs on.\n")

	for _, p := range profiles {
		fmt.Fprintf(&b, "\n## `%s`\n\n", p.name)
		fmt.Fprintf(&b, "Refuses to run where the Landlock ABI is below **%s**.\n\n", p.abi)
		b.WriteString("Writable: " + backticked(p.write) + "\n\n")
		if len(p.writeTree) > 0 {
			b.WriteString("Writable device trees: " + backticked(p.writeTree) + "\n\n")
		}
		if len(p.writeDevice) > 0 {
			b.WriteString("Writable device nodes, read/write/truncate only: " +
				backticked(p.writeDevice) + "\n\n")
		}
		fmt.Fprintf(&b, "Refused, %d syscalls: %s\n", len(p.refused), strings.Join(p.refused, ", "))
	}
	b.WriteString("\n## Attaching a debugger\n\n")
	b.WriteString("Every process the supervisor spawns gets its **own** Landlock domain, and Landlock\n" +
		"refuses `ptrace` between sibling domains \u2014 which two commands in the same sandbox are.\n" +
		"So attaching to a process that is already running fails with `Operation not permitted`\n" +
		"on every flavor, including `dev`, whose profile leaves `ptrace` out of its refusal list\n" +
		"on purpose. One command also cannot read another's `/proc/<pid>/exe`.\n\n")
	b.WriteString("**Launching a program under a debugger works**, on `dev`: a child inherits its\n" +
		"parent's domain, so it is not a sibling. That is the whole of what `dev` buys here and\n" +
		"what `base` refuses. Neither image ships a debugger, so this is about what you install\n" +
		"into a `dev` sandbox. Why it is not a per-flavor knob is D33 in `docs/decisions.md`.\n")
	return b.String(), nil
}

// hostTools asks `kelyfos serve-mcp` for its own tools/list, over the protocol,
// the way a client would. Driving the server rather than reading a table means
// the page cannot describe a surface the server does not actually advertise —
// which is the same reason the guest's half comes from --dump-tools (E4-1).
func hostTools(bin string) ([]mcp.Tool, error) {
	cmd := exec.Command(bin, "serve-mcp")
	cmd.Stdin = strings.NewReader(strings.Join([]string{
		`{"jsonrpc":"2.0","id":1,"method":"initialize","params":{"protocolVersion":"2025-11-25","capabilities":{},"clientInfo":{"name":"gendocs","version":"1"}}}`,
		`{"jsonrpc":"2.0","method":"notifications/initialized"}`,
		`{"jsonrpc":"2.0","id":2,"method":"tools/list"}`,
		"",
	}, "\n"))
	var buf strings.Builder
	cmd.Stdout = &buf
	if err := cmd.Run(); err != nil {
		if _, ok := err.(*exec.ExitError); !ok {
			return nil, err
		}
	}
	for _, line := range strings.Split(buf.String(), "\n") {
		if !strings.Contains(line, `"tools"`) {
			continue
		}
		var resp struct {
			Result struct {
				Tools []mcp.Tool `json:"tools"`
			} `json:"result"`
		}
		if err := json.Unmarshal([]byte(line), &resp); err == nil && len(resp.Result.Tools) > 0 {
			return resp.Result.Tools, nil
		}
	}
	return nil, fmt.Errorf("serve-mcp did not answer tools/list")
}

func toolsPage(sup, bin string) (string, error) {
	text, err := capture(sup, "--dump-tools")
	if err != nil {
		return "", fmt.Errorf("asking the supervisor for its tools: %w", err)
	}
	var d toolDump
	if err := json.Unmarshal([]byte(text), &d); err != nil {
		return "", fmt.Errorf("reading the supervisor's tool list: %w", err)
	}

	var b strings.Builder
	b.WriteString(banner)
	b.WriteString("\n# MCP tools\n\n" +
		"What an agent attached to a sandbox can call, exactly as the guest advertises\n" +
		"it in `tools/list`. Attach with `kelyfos mcp`.\n\n" +
		"Which tools appear depends on what the sandbox is: the team tools exist only\n" +
		"for a sandbox in a team, and `team_spawn` only for an agent whose policy\n" +
		"granted a spawn budget. A tool that is always advertised and always fails\n" +
		"teaches a model to ignore failures, so it is not advertised (F-D18).\n\n" +
		"A `[[plugin]]` in `kelyfos.toml` adds its own tools on top of these, namespaced\n" +
		"under the plugin's name. They come from that server rather than from KelyfOS,\n" +
		"so they are not listed here — `tools/list` on a running sandbox is the only\n" +
		"complete answer for a machine that has one.\n")

	host, err := hostTools(bin)
	if err != nil {
		return "", fmt.Errorf("asking serve-mcp for its tools: %w", err)
	}

	groups := []struct {
		title string
		doc   string
		tools []mcp.Tool
	}{
		{"Every sandbox", "Always available.", d.Base},
		{"In a team", "Added when this sandbox is a member of a team.", d.Team},
		{"With a spawn budget", "Added when the team policy granted this agent one.", d.TeamSpawn},
	}
	for _, g := range groups {
		fmt.Fprintf(&b, "\n## %s\n\n%s\n", g.title, g.doc)
		for _, t := range g.tools {
			fmt.Fprintf(&b, "\n### `%s`\n\n%s\n\n", t.Name, t.Description)
			if len(t.InputSchema.Properties) == 0 {
				b.WriteString("No parameters.\n")
				continue
			}
			required := map[string]bool{}
			for _, r := range t.InputSchema.Required {
				required[r] = true
			}
			names := make([]string, 0, len(t.InputSchema.Properties))
			for n := range t.InputSchema.Properties {
				names = append(names, n)
			}
			sort.Strings(names)
			b.WriteString("| Parameter | Type | Required | Meaning |\n| --- | --- | --- | --- |\n")
			for _, n := range names {
				p := t.InputSchema.Properties[n]
				typ := p.Type
				if p.Items != nil {
					typ += " of " + p.Items.Type
				}
				req := "no"
				if required[n] {
					req = "**yes**"
				}
				fmt.Fprintf(&b, "| `%s` | %s | %s | %s |\n", n, typ, req, cell(p.Description))
			}
		}
	}
	// The other direction: what a client attached to `kelyfos serve-mcp` sees.
	// Two surfaces in one page because a reader asking "what tools are there"
	// means both, and the difference between them is which side of the wall the
	// caller is on.
	b.WriteString("\n---\n\n## Driving KelyfOS from outside: `kelyfos serve-mcp`\n\n" +
		"These are the host's tools, not a guest's. An MCP client that runs\n" +
		"`kelyfos serve-mcp` gets them, and can boot sandboxes rather than work inside\n" +
		"one. Everything they do is bounded by the project's `kelyfos.toml`, and none of\n" +
		"them can widen it (`docs/mcp-surface.md`).\n")
	writeTools(&b, host)

	return b.String(), nil
}

// writeTools renders one group of tools with their parameters.
func writeTools(b *strings.Builder, tools []mcp.Tool) {
	for _, t := range tools {
		fmt.Fprintf(b, "\n### `%s`\n\n%s\n\n", t.Name, t.Description)
		if len(t.InputSchema.Properties) == 0 {
			b.WriteString("No parameters.\n")
			continue
		}
		required := map[string]bool{}
		for _, r := range t.InputSchema.Required {
			required[r] = true
		}
		names := make([]string, 0, len(t.InputSchema.Properties))
		for n := range t.InputSchema.Properties {
			names = append(names, n)
		}
		sort.Strings(names)
		b.WriteString("| Parameter | Type | Required | Meaning |\n| --- | --- | --- | --- |\n")
		for _, n := range names {
			p := t.InputSchema.Properties[n]
			typ := p.Type
			if p.Items != nil {
				typ += " of " + p.Items.Type
			}
			req := "no"
			if required[n] {
				req = "**yes**"
			}
			fmt.Fprintf(b, "| `%s` | %s | %s | %s |\n", n, typ, req, cell(p.Description))
		}
	}
}

// cell makes a string safe inside a markdown table: a pipe would end the column
// and a newline would end the row.
func cell(s string) string {
	s = strings.ReplaceAll(s, "|", `\|`)
	return strings.Join(strings.Fields(s), " ")
}

func or(s, fallback string) string {
	if strings.TrimSpace(s) == "" {
		return fallback
	}
	return s
}
